#!/usr/bin/env python3
from numpy import empty
from PIL import Image
from bitstring import BitStream
from sys import argv

try:
    fn = argv[1]
except:
    fn = 'sol'

f = open(fn, 'rb')
b = BitStream(f)
b.read(52*8)

a = empty((256, 256))
for j in range(256):
	for i in range(256):
		a[j][i] = b.read(12).int

img = Image.fromarray(a, mode='I')
img.save('sol.tiff')

