# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'dorta'

google-ID: 'UA-117915917-3'

menu:
- {name: 'About', path: 'menu', url: 'about.html'}
- {name: 'Writing', path: 'menu', url: 'writing.html'}
- {name: 'Books', path: 'menu', url: 'book.html'}
- {name: 'Codes', path: 'menu', url: 'code.html'}
- {name: 'Contact', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/diegohdorta'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/diego-dorta-059465131/'}
- {icon: 'envelope', link: 'mailto:diego.dorta@nxp.com'}
- {icon: 'instagram', link: 'https://www.instagram.com/diegohdorta/'}
- {icon: 'spotify', link: 'spotify:user:diegohdorta:playlist:25pUm8SDTIPBRFdB8QbXmv'}
- {icon: 'rss-square', link: 'rss-feed.xml'}

pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
