######################################################################
# Automatically generated by qmake (3.0) qua fev 8 12:52:59 2017
######################################################################

TEMPLATE = app
TARGET = hello_world
INCLUDEPATH += .
QT += core gui
QT += opengl 

# Input
SOURCES += main.cpp
