######################################################################
# Automatically generated by qmake (3.0) sex mar 3 14:26:17 2017
######################################################################

QT += widgets
QT += core

CONFIG+= qt debug c++14

TEMPLATE = app
TARGET = demo_imx7
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
